jit/config/routes.rb
Rails.application.routes.draw do

  

  resources :evaluations do
    resources :questions
    resources :users
  end

  resources :ratings

  devise_for :users
  get 'sessions/new'
  post 'sessions/create'
  delete 'sessions/destroy'

  get 'users/change'

  get 'questions/show'

  get 'assignments/qlist'

  get 'questions/commentlist'

  get 'users/hwlist' # Anna made a route! 9 February 2015
                     
  post 'questions/save_all'
  
  resources :users do
    resources :memberships
    resources :groups
    resources :questions
  end

  resources :memberships

  resources :groups do
    resources :memberships
    resources :users
  end

  resources :assignments do 
    resources :questions
  end

  resources :questions do
    resources :ratings
    resources :evaluations
  end

  root to: "home#index" #homepage

end

jit/app/models/rating.rb
class Rating < ActiveRecord::Base
	belongs_to :user
	belongs_to :question

	validates_inclusion_of :discuss, in: [true, false]
end

jit/app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]


  respond_to :html



  def index
    @ratings = Rating.all
    @questions = Question.all
    respond_with(@ratings)
  end

  def show
    #@ratings = Rating.all
    #respond_with(@rating)
    redirect_to questions_path
  end

  def new
    @rating = Rating.new
    respond_with(@rating)
  end

  def edit
  end

  def create
    @rating = Rating.new(rating_params)
    @rating.save
    if @rating.discuss?
      @question = Question.find(Question.where(id: @rating.question_id))
      @question.update(votes: @question.votes += 1)
    end 
    @question = Question.find(Question.where(id: @rating.question_id))
    @question.update(percentage: @question.votes.to_f / @question.ratings.count)
    respond_with(@rating)
  end

  def update
    @rating.update(rating_params)
    respond_with(@rating)
  end

  def destroy
    @rating.destroy
    respond_with(@rating)
  end

  private
    def set_rating
      @rating = Rating.find(params[:id])
    end

    def rating_params
      params.require(:rating).permit(:discuss, :user_id, :question_id, :comment)
    end
end

jit/app/helpers/ratings_helper.rb
module RatingsHelper
end

jit/app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%#= f.submit %>
  </div>
<% end %>

jit/app/views/ratings/_promoter.html.erb
<h1> Promoter View </h2>

	<table class="table table-bordered">
		<thead>
			<th>Question</th>
			<th>Rating</th>
		</thead>

		<tbody>
			<% @questions.each do |question| %>
			<td><%= question.content %></td>
			<td>


				<%= form_for(Rating.new) do |g| %>
				<%= g.hidden_field :user_id, value: @user.id %>
				<%= g.hidden_field :question_id, value: question.id %>
            	<p> <%= g.radio_button :discuss, true %>Discuss </p>
            	<p> <%= g.radio_button :discuss, false %>Pass </p>

            	<p> <%= g.submit "Save"%> </p>
            	
 
            		
            		
            	<%end%>
			</td>

		</tbody>
	
	<% end %>

jit/app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

jit/app/views/ratings/index.html.erb
<h1>Listing ratings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

jit/app/views/ratings/new.html.erb
<br><br>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

jit/app/views/ratings/show.html.erb
<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>