jit/config/routes.rb
Rails.application.routes.draw do

  

  resources :evaluations do
    resources :questions
    resources :users
  end

  resources :ratings

  devise_for :users
  get 'sessions/new'
  post 'sessions/create'
  delete 'sessions/destroy'

  get 'users/change'

  get 'questions/show'

  get 'assignments/qlist'

  get 'questions/commentlist'

  get 'users/hwlist' # Anna made a route! 9 February 2015
                     
  post 'questions/save_all'
  
  resources :users do
    resources :memberships
    resources :groups
    resources :questions
  end

  resources :memberships

  resources :groups do
    resources :memberships
    resources :users
  end

  resources :assignments do 
    resources :questions
  end

  resources :questions do
    resources :ratings
    resources :evaluations
  end

  root to: "home#index" #homepage

end

jit/app/models/assignment.rb
class Assignment < ActiveRecord::Base
	has_many :questions
	def self.current
		Assignment.all.order("writer_due").last || nil
	end

	def current?
		self === Assignment.current
	end		
end

jit/app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json # for web-service support; on respond_to/with.... http://www.justinweiss.com/blog/2014/11/03/respond-to-without-all-the-pain/

  # re: .html and .json responses... http://stackoverflow.com/questions/20188047/rails-respond-to-json-and-html
  # but what does above/below /do/, in English? 

  def qlist
    @assignment = Assignment.find(params[:assignment])
    @question_flags = []
    for i in 1..3
      @question_flags[i] = @assignment.questions.where(description_flag: i).where.not(content: "").order('percentage desc')
    end

    @questions_flag_1 = @assignment.questions.where(description_flag: 1).where.not(content: "").order('percentage desc')
    @questions_flag_2 = @assignment.questions.where(description_flag: 2).where.not(content: "").order('percentage desc')
    @questions_flag_3 = @assignment.questions.where(description_flag: 3).where.not(content: "").order('percentage desc')
  end


  def index
    @assignments = Assignment.all
  end

  def show
  end

  def new
    @assignment = Assignment.new
  end

  def edit
  end

  def create
    @assignment = Assignment.new(assignment_params)
    @assignments = Assignment.where.not(id: @assignment.id)

    flash[:notice] = "Assignment created. [Applause]!" if @assignment.save
    respond_with(@assignment)


    if @assignment.active?
      @assignments.each do |assignment|
        assignment.update(active: false)
      end
      if @assignment.id % 2 == 0
        Group.update(Group.where(name: 'Group 2'), :writer => true)
        Group.update(Group.where(name: 'Group 1'), :writer => false)
      else
        Group.update(Group.where(name: 'Group 2'), :writer => false)
        Group.update(Group.where(name: 'Group 1'), :writer => true)
      end
    end
    
  end

  def update # could this action/method also be shortened to the above format? how/why?
    @assignments = Assignment.where.not(id: @assignment.id)
    respond_to do |format|
      if @assignment.update(assignment_params) #if all went well, assignment now updated
        format.html { redirect_to :action => 'index'}
        format.json { render :show, status: :ok, location: @assignment }
      else # otherwise, assignment not updated: throw error
        format.html { render :edit }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end

    if @assignment.active?
      @assignments.each do |assignment|
        assignment.update(active: false)
      end
      if @assignment.id % 2 == 0
        Group.update(Group.where(name: 'Group 2'), :writer => true)
        Group.update(Group.where(name: 'Group 1'), :writer => false)
      else
        Group.update(Group.where(name: 'Group 2'), :writer => false)
        Group.update(Group.where(name: 'Group 1'), :writer => true)
      end
    end
  end

  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to assignments_url, notice: 'Assignment destroyed. You monster!' } #doesn't show! why not?
      format.json { head :no_content } 
  end
end

  private 
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    def assignment_params
      params.require(:assignment).permit(:title, :description, :writer_due, :promoter_due, :active, :description_2, :description_3, :reveal_1, :reveal_2, :reveal_3, :percent_1, :percent_2, :percent_3)
    end
end

jit/app/helpers/assignments_helper.rb
module AssignmentsHelper
end

jit/app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f| %>
  <div class='row'>
    <div class='col-md-8'>
      <% if @assignment.errors.any? %>

        <div id="error_explanation">

          <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

          <ul>
          <% @assignment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>

        </div>

      <% end %>


      <%#displays form table for entering new assignment details%>
      <div class="form-group">
        <%= f.label :title, class:'control-label' %><%#automatically capitalizes labels%>
        <%= f.text_field :title, class:'form-control'%>
      </div>
      <hr>
      <% for i in 1..3 %>

        <div class="form-group">
          <% if i == 1 
              item = "description"
             else
              item = "description_#{i}"
             end
             %>
          <%= f.label item, "Prompt #{i}", class:'control-label' %>
          <%= f.text_area item, class:'form-control', rows:4%>
          <% if @assignment["percent_#{i}"] == 0%>
          <%= f.hidden_field "reveal_#{i}", value: false %>
          <% else%>
          <%= f.hidden_field "reveal_#{i}", value: true%>
          <%end%>
        </div>
        <div class='form-group'>

          <div class='input-group'>
            <div class="input-group-addon">Show </div>
            <%= f.text_field "percent_#{i}", class:'form-control'%>
            <div class="input-group-addon">% of submissions to Promoters</div>
          </div>

          <p class='help-block'>Note: if the above percentage is 50 and there are 40 student submissions for this prompt, promoters will be asked to complete promotions on a subset of 20 of those submissions.</p>

        </div>
        <hr>
      <% end %>

     

    <br>

      <div class="field">
        <%= f.label :writing_due %><br>
        <%= f.datetime_select :writer_due %>
      </div>
      <div class="field">
        <%= f.label :promoting_due %><br>
        <%= f.datetime_select :promoter_due %>
      </div>

    <br>

      <div class="actions">
        <%= f.submit class:'btn btn-primary' %>
      </div>


    <% end %>
  </div>
</div>

jit/app/views/assignments/edit.html.erb
<h1>Edit Assignment</h1>

<br>

<%= render 'form' %>

<br><br>

<%= link_to 'Back to Assignments', assignments_path %>

jit/app/views/assignments/index.html.erb
<%# Admins only %> 
<%if current_user.admin?%>
  <div class='page-header'>
    <h1>Assignments </h1>

  </div>
  <p><%= link_to 'New Assignment', new_assignment_path, class:'btn btn-primary' %></p>  
<table class="table table-bordered"> <%#table style (with borders around all cells); bordered, striped, hover all possible%>
  
  <thead> <%#table header%>
    <tr>
      <th>Title</th>
      <th>Due Dates</th> 
      <th class='text-center'>Submissions</th>
      <th class='text-center'>Actions</th>
    </tr>
  </thead>

  <tbody class='table-center'>
    <% @assignments.each do |assignment| %> <%#table content: each row contains...%>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <% if assignment.current? %>
        <tr bgcolor="#ededed">

        <%end%>

        <td><%= assignment.title %></td>
        <td>Writing: <%= assignment.writer_due.strftime('%-B %-d, %Y at %I:%M%p') %>
            <br>
            Promoting: <%= assignment.promoter_due.strftime('%-B %-d, %Y at %I:%M%p') %></td>
        <td class='text-center'><%= link_to 'See all', {:controller => "assignments", :action => "qlist", :assignment => assignment.id}, class:'btn btn-link' %>
        </td>

        <td class='text-center'><%= link_to "<i class='glyphicon glyphicon-pencil'></i>".html_safe, edit_assignment_path(assignment), class:'btn btn-warning' %>
        <%= link_to "<i class='glyphicon glyphicon-trash'></i>".html_safe, assignment, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td> 
        <%# why does it ask me to confirm several times (usually, but not always? %>        
      </tr>

    <% end %>
  </tbody>

</table>

<p> Current assignment is shaded. </p>




<%else%>
<h3>You do not have access to this page</h3>
<%end%>

jit/app/views/assignments/new.html.erb
<h1>New Assignment</h1> 

<br>

<%= render 'form' %> 

<br><br>

<%= link_to 'Back to Assignments', assignments_path %>

jit/app/views/assignments/qlist.html.erb
<div class='page-header'>
	<h1> Submissions for Assignment </h1>
</div>
<p> Favorite submissions are shaded. </p>

<% for i in 1..3 %>
<h2 class='h4'>Prompt <%= i %>: <%=
	if i==1
		@assignment.description
	else
		@assignment["description_#{i}"]
	end
	%></h4> 

<table class="table table-bordered">
		<thead>
			<th style="width: 9%">Favorite</th>
			<th style="width: 51%">Submission</th>
			<th style="width: 16%">Writer</th>
			<th style="width: 16%">Email</th>
			<th style="width: 10%">Comments</th>
			<th style="width: 24%">Student Rating</th>
		</thead>
		<tbody>
			<% @question_flags[i].each do |question| %>
			<%= form_for(question) do |f| %>
			<tr>
				<%if question.prof_choice%>
				<tr bgcolor="#ededed">
					<%end%>
			<td><%if question.prof_choice%>
					<%= f.hidden_field :prof_choice, value: false%>
					<%= f.submit "Deselect", class:'btn btn-default'%>
				</button>
				<%else%>
					<%= f.hidden_field :prof_choice, value: true%>
					<%= f.submit "Select", class:'btn btn-default'%>
				<%end%>
				</td>
			<td><%= question.content %></td>
			<td><%= question.user.name %></td>
			<td><%= question.user.email %> </td>
			<td><%= link_to 'Comments', {:controller => "questions", :action => "commentlist", :question => question.id} %></td>
			<td><% if question.ratings.count != 0%>
				<%=question.votes * 100 / question.ratings.count%>% 
				<%end%> </td>
				<% end %>
			
			
		</tr>
		</tbody>
		<% end %>
</table>
<% end %>


<%= link_to 'Back to Assignments', assignments_path %>

jit/app/views/assignments/show.html.erb
<%# Admins only %>




<br>

<p>
  <strong>Title:</strong>
  <%= @assignment.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @assignment.description %>
</p>

<br><br>

<%= link_to 'Back to Assignments', assignments_path %>